import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import fs from 'node:fs/promises';
import path from 'node:path';
const child=spawn(process.execPath,['test/ui-session.mjs'],{windowsHide:true,stdio:['ignore','pipe','pipe']});
const ready=await new Promise(resolve=>createInterface({input:child.stdout}).once('line',l=>resolve(JSON.parse(l))));
const url=new URL(ready.url),headers={'x-workspace-token':url.hash.slice(1)};
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
await page.addInitScript(folder=>{window.__hosts=[];const handlers=[];document.addEventListener("keydown",e=>{if(e.ctrlKey&&e.code==="KeyS"){e.preventDefault();handlers.forEach(fn=>fn({data:{type:"shortcut",command:"save-file"}}));}});window.chrome||={};window.chrome.webview={addEventListener(_,fn){handlers.push(fn);},postMessage(m){window.__hosts.push(m.action);if(m.requestId)queueMicrotask(()=>handlers.forEach(fn=>fn({data:{type:'response',requestId:m.requestId,result:m.action==='chooseFolder'?folder:true}})));}};},ready.data);
try{
 await page.goto(ready.url);await page.locator('#editor-name').filter({hasText:'review.md'}).waitFor();
 await page.locator('#new-note').click();await page.locator('#text-editor').waitFor();
 assert.equal(await page.locator('#text-editor').evaluate(e=>e===document.activeElement),true);
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/local/draft')&&r.request().postDataJSON()?.text==='まず思いついたことを書く。'),page.locator('#text-editor').fill('まず思いついたことを書く。')]);
 assert.equal(await page.evaluate(()=>__hosts.filter(x=>x==='chooseFolder').length),1);
 await page.reload();await page.locator('#text-editor').waitFor();assert.equal(await page.locator('#text-editor').inputValue(),'まず思いついたことを書く。');
 const saved=page.waitForResponse(r=>r.url().endsWith('/api/notes/save')&&r.ok());
 await page.locator('#text-editor').press('Control+s');const note=await(await saved).json();
 assert.equal(path.dirname(note.path),ready.data);assert.equal(await fs.readFile(note.path,'utf8'),'まず思いついたことを書く。');
 assert.equal(await page.locator('#dialog').isVisible(),false);
 await page.locator('#text-editor').fill('追記しました。');
 const update=page.waitForResponse(r=>r.url().endsWith('/api/local/file')&&r.request().method()==='POST'&&r.ok());
 await page.locator('#text-editor').press('Control+s');await update;assert.equal(await fs.readFile(note.path,'utf8'),'追記しました。');
 await page.locator('#new-note').click();await page.locator('#text-editor').waitFor();assert.equal(await page.evaluate(()=>__hosts.filter(x=>x==='chooseFolder').length),0);
 await page.locator('#save-file').click();await page.screenshot({path:'.test-data/note-save.png'});
 assert.deepEqual(errors,[]);console.log('PASS: folder chosen once, instant note, autosaved draft restored, Ctrl+S saves without a dialog, subsequent edits save to same file');
}finally{await browser.close();await fetch(url.origin+'/api/shutdown',{method:'POST',headers}).catch(()=>{});child.kill();}
